rule all:
    input: "cool_hello_world.txt"

rule make_cool:
    input: "hello_world.txt"
    output: "cool_hello_world.txt"
    shell: "echo xXxXx $(cat hello_world.txt) xXxXx > cool_hello_world.txt"

rule hello_world:
    output: "hello_world.txt"
    shell: "echo Hello World! > hello_world.txt"
